add_newline = false

[username]
format = "[$user](red) on "
show_always = true

[directory]
style = "red"
format = "[$path]($style)"
truncate_to_repo = false

[git_branch]
style = "white"
format = " $branch"

[git_status]
modified = "*"
deleted = "*"
renamed = "*"
ahead = "â‡¡"
behind = "â‡£"
untracked = ""
format = "[$staged](yellow)[$modified](yellow)[$deleted](red)[$renamed](blue)[$ahead](green)[$behind](red) "

[package]
disabled = true

[golang]
format = '[ğŸ¹ $version]($style) '

[rust]
format = '[ğŸ¦€ $version]($style) '

[python]
format = '[ğŸ $version]($style) '

[ruby]
format = '[ğŸ’ $version]($style) '

[lua]
format = '[ğŸŒ™ $version]($style) '

[cmd_duration]
style = "red"
min_time = 1000
format = "\nRun in [$duration]($style)"
# show_milliseconds = true

[character]
success_symbol = "Î»"
error_symbol = "Î»"
