format = "$username$directory$git_branch$git_status$cmd_duration\n$character"
add_newline = false

[username]
format = "[$user](red) on "
show_always = true

[directory]
style = "red"
format = "[$path]($style)"
truncate_to_repo = false

[git_branch]
style = "white"
format = " $branch"

[git_status]
modified = "*"
deleted = "*"
renamed = "*"
ahead = "⇡"
behind = "⇣"
untracked = ""
format = "[$staged](yellow)[$modified](yellow)[$deleted](red)[$renamed](blue)[$ahead](green)[$behind](red) "

[cmd_duration]
style = "red"
min_time = 1000
format = "\nRun in [$duration]($style)"

[character]
success_symbol = "λ"
error_symbol = "λ"
vimcmd_symbol = "A"
vimcmd_replace_symbol = "B"
vimcmd_visual_symbol = "C"
