general.import = [
	"colors.toml"
]

[font]
size = 14
normal = { family = "CaskaydiaCove Nerd Font" }
bold = { family = "CaskaydiaCove Nerd Font" }
italic = { family = "CaskaydiaCove Nerd Font" }

[window]
decorations = "none"
opacity = 0.98
padding = { x = 10, y = 1 }
